name: CI

on: [push]

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node-version }}"
          cache: "yarn"

      - uses: actions/cache@v2
        with:
          path: "~/.cache/yarn"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Typecheck, format check, and lint
        run: |
          yarn typecheck &
          yarn format:check &
          yarn lint &
          wait

      - name: Test
        run: yarn test:ci

      - name: Build
        run: yarn build
